# Generated by Django 2.0.2 on 2018-05-31 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shops',
            options={'ordering': ['company_name']},
        ),
        migrations.AlterField(
            model_name='poll',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 18, 34, 48, 383145)),
        ),
    ]
