# Generated by Django 2.0.2 on 2018-05-31 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20180531_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shops',
            options={},
        ),
        migrations.AlterField(
            model_name='poll',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 18, 41, 57, 741696)),
        ),
    ]
