# Generated by Django 2.0.2 on 2018-05-31 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20180531_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 18, 43, 51, 859325)),
        ),
    ]
