# Generated by Django 2.0.2 on 2018-06-01 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20180531_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 1, 22, 42, 29, 848642)),
        ),
    ]
