# Generated by Django 2.0.2 on 2018-06-03 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20180602_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 11, 23, 2, 367258)),
        ),
    ]
